name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Build
      run: ./build.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/setup-wsl-open-amd64
          dist/setup-wsl-open-arm64
